agents:
  fantasy_draft_agentcore:
    entrypoint: fantasy_draft_agentcore.py
    name: fantasy_draft_agentcore
    aws:
      account: "120687070694"
      execution_role: arn:aws:iam::120687070694:role/fantasy-draft-agentcore-role
      region: us-east-1
      ecr_repository: fantasy-draft-agentcore
    build:
      requirements_file: requirements.txt
      auto_create_ecr: true