#!/usr/bin/env python3
"""
Generate comprehensive mock fantasy football rankings data
Creates 500+ players with realistic names, teams, positions, ADP, and tiers
"""

# NFL Teams for realistic distribution
NFL_TEAMS = [
    'ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE', 'DAL', 'DEN',
    'DET', 'GB', 'HOU', 'IND', 'JAX', 'KC', 'LV', 'LAC', 'LAR', 'MIA',
    'MIN', 'NE', 'NO', 'NYG', 'NYJ', 'PHI', 'PIT', 'SF', 'SEA', 'TB',
    'TEN', 'WAS'
]

def get_tier_from_rank(rank):
    """Calculate tier based on rank ranges"""
    if rank <= 12:
        return 1
    elif rank <= 36:
        return 2
    elif rank <= 60:
        return 3
    elif rank <= 100:
        return 4
    elif rank <= 150:
        return 5
    elif rank <= 200:
        return 6
    elif rank <= 300:
        return 7
    else:
        return 8

def generate_adp(rank):
    """Generate realistic ADP with some variance from exact rank"""
    import random
    # ADP should be close to rank but with some variance
    variance = random.uniform(-5, 10)  # Slightly positive bias for late round sleepers
    return max(1.0, round(rank + variance, 1))

# Complete player database
COMPREHENSIVE_RANKINGS = [
    # TIER 1 - Elite (Ranks 1-12)
    {"rank": 1, "name": "Saquon Barkley", "team": "PHI", "position": "RB", "adp": 1.2, "tier": 1},
    {"rank": 2, "name": "Josh Allen", "team": "BUF", "position": "QB", "adp": 2.1, "tier": 1},
    {"rank": 3, "name": "Lamar Jackson", "team": "BAL", "position": "QB", "adp": 3.5, "tier": 1},
    {"rank": 4, "name": "CeeDee Lamb", "team": "DAL", "position": "WR", "adp": 2.8, "tier": 1},
    {"rank": 5, "name": "Justin Jefferson", "team": "MIN", "position": "WR", "adp": 3.2, "tier": 1},
    {"rank": 6, "name": "Patrick Mahomes", "team": "KC", "position": "QB", "adp": 6.1, "tier": 1},
    {"rank": 7, "name": "Tyreek Hill", "team": "MIA", "position": "WR", "adp": 4.5, "tier": 1},
    {"rank": 8, "name": "Jahmyr Gibbs", "team": "DET", "position": "RB", "adp": 7.8, "tier": 1},
    {"rank": 9, "name": "Bijan Robinson", "team": "ATL", "position": "RB", "adp": 8.2, "tier": 1},
    {"rank": 10, "name": "Dak Prescott", "team": "DAL", "position": "QB", "adp": 10.5, "tier": 1},
    {"rank": 11, "name": "Ja'Marr Chase", "team": "CIN", "position": "WR", "adp": 11.3, "tier": 1},
    {"rank": 12, "name": "Amon-Ra St. Brown", "team": "DET", "position": "WR", "adp": 12.1, "tier": 1},

    # TIER 2 - Elite/High-End (Ranks 13-36)
    {"rank": 13, "name": "Puka Nacua", "team": "LAR", "position": "WR", "adp": 13.7, "tier": 2},
    {"rank": 14, "name": "Breece Hall", "team": "NYJ", "position": "RB", "adp": 14.2, "tier": 2},
    {"rank": 15, "name": "Jonathan Taylor", "team": "IND", "position": "RB", "adp": 15.8, "tier": 2},
    {"rank": 16, "name": "Christian McCaffrey", "team": "SF", "position": "RB", "adp": 16.4, "tier": 2},
    {"rank": 17, "name": "Travis Kelce", "team": "KC", "position": "TE", "adp": 17.1, "tier": 2},
    {"rank": 18, "name": "Anthony Richardson", "team": "IND", "position": "QB", "adp": 18.3, "tier": 2},
    {"rank": 19, "name": "Cooper Kupp", "team": "LAR", "position": "WR", "adp": 19.2, "tier": 2},
    {"rank": 20, "name": "Stefon Diggs", "team": "HOU", "position": "WR", "adp": 20.1, "tier": 2},
    {"rank": 21, "name": "Derrick Henry", "team": "BAL", "position": "RB", "adp": 21.5, "tier": 2},
    {"rank": 22, "name": "Kyler Murray", "team": "ARI", "position": "QB", "adp": 22.3, "tier": 2},
    {"rank": 23, "name": "A.J. Brown", "team": "PHI", "position": "WR", "adp": 23.1, "tier": 2},
    {"rank": 24, "name": "Mike Evans", "team": "TB", "position": "WR", "adp": 24.2, "tier": 2},
    {"rank": 25, "name": "Tee Higgins", "team": "CIN", "position": "WR", "adp": 25.4, "tier": 2},
    {"rank": 26, "name": "DK Metcalf", "team": "SEA", "position": "WR", "adp": 26.1, "tier": 2},
    {"rank": 27, "name": "DeVonta Smith", "team": "PHI", "position": "WR", "adp": 27.3, "tier": 2},
    {"rank": 28, "name": "Keenan Allen", "team": "CHI", "position": "WR", "adp": 28.7, "tier": 2},
    {"rank": 29, "name": "Joe Burrow", "team": "CIN", "position": "QB", "adp": 29.2, "tier": 2},
    {"rank": 30, "name": "Amari Cooper", "team": "CLE", "position": "WR", "adp": 30.1, "tier": 2},
    {"rank": 31, "name": "Josh Jacobs", "team": "GB", "position": "RB", "adp": 31.4, "tier": 2},
    {"rank": 32, "name": "Isiah Pacheco", "team": "KC", "position": "RB", "adp": 32.2, "tier": 2},
    {"rank": 33, "name": "Jalen Hurts", "team": "PHI", "position": "QB", "adp": 33.1, "tier": 2},
    {"rank": 34, "name": "Mark Andrews", "team": "BAL", "position": "TE", "adp": 34.3, "tier": 2},
    {"rank": 35, "name": "Kenneth Walker III", "team": "SEA", "position": "RB", "adp": 35.2, "tier": 2},
    {"rank": 36, "name": "Davante Adams", "team": "LV", "position": "WR", "adp": 36.1, "tier": 2},

    # TIER 3 - High-End (Ranks 37-60)
    {"rank": 37, "name": "Chris Olave", "team": "NO", "position": "WR", "adp": 37.4, "tier": 3},
    {"rank": 38, "name": "Drake London", "team": "ATL", "position": "WR", "adp": 38.2, "tier": 3},
    {"rank": 39, "name": "Garrett Wilson", "team": "NYJ", "position": "WR", "adp": 39.1, "tier": 3},
    {"rank": 40, "name": "DJ Moore", "team": "CHI", "position": "WR", "adp": 40.2, "tier": 3},
    {"rank": 41, "name": "Rhamondre Stevenson", "team": "NE", "position": "RB", "adp": 41.3, "tier": 3},
    {"rank": 42, "name": "Caleb Williams", "team": "CHI", "position": "QB", "adp": 42.1, "tier": 3},
    {"rank": 43, "name": "Malik Nabers", "team": "NYG", "position": "WR", "adp": 43.4, "tier": 3},
    {"rank": 44, "name": "Tony Pollard", "team": "TEN", "position": "RB", "adp": 44.2, "tier": 3},
    {"rank": 45, "name": "Sam LaPorta", "team": "DET", "position": "TE", "adp": 45.1, "tier": 3},
    {"rank": 46, "name": "Marvin Harrison Jr.", "team": "ARI", "position": "WR", "adp": 46.3, "tier": 3},
    {"rank": 47, "name": "Aaron Jones", "team": "MIN", "position": "RB", "adp": 47.2, "tier": 3},
    {"rank": 48, "name": "Tua Tagovailoa", "team": "MIA", "position": "QB", "adp": 48.1, "tier": 3},
    {"rank": 49, "name": "Terry McLaurin", "team": "WAS", "position": "WR", "adp": 49.4, "tier": 3},
    {"rank": 50, "name": "Calvin Ridley", "team": "TEN", "position": "WR", "adp": 50.5, "tier": 3},
    {"rank": 51, "name": "Rachaad White", "team": "TB", "position": "RB", "adp": 51.2, "tier": 3},
    {"rank": 52, "name": "Rome Odunze", "team": "CHI", "position": "WR", "adp": 52.3, "tier": 3},
    {"rank": 53, "name": "Jayden Daniels", "team": "WAS", "position": "QB", "adp": 53.1, "tier": 3},
    {"rank": 54, "name": "George Pickens", "team": "PIT", "position": "WR", "adp": 54.4, "tier": 3},
    {"rank": 55, "name": "Brock Purdy", "team": "SF", "position": "QB", "adp": 55.2, "tier": 3},
    {"rank": 56, "name": "Courtland Sutton", "team": "DEN", "position": "WR", "adp": 56.1, "tier": 3},
    {"rank": 57, "name": "De'Von Achane", "team": "MIA", "position": "RB", "adp": 57.3, "tier": 3},
    {"rank": 58, "name": "Brandon Aiyuk", "team": "SF", "position": "WR", "adp": 58.2, "tier": 3},
    {"rank": 59, "name": "Evan Engram", "team": "JAX", "position": "TE", "adp": 59.1, "tier": 3},
    {"rank": 60, "name": "Jordan Love", "team": "GB", "position": "QB", "adp": 60.3, "tier": 3},

    # TIER 4 - Mid-Range (Ranks 61-100)
    {"rank": 61, "name": "Tank Dell", "team": "HOU", "position": "WR", "adp": 61.2, "tier": 4},
    {"rank": 62, "name": "Diontae Johnson", "team": "CAR", "position": "WR", "adp": 62.4, "tier": 4},
    {"rank": 63, "name": "James Cook", "team": "BUF", "position": "RB", "adp": 63.1, "tier": 4},
    {"rank": 64, "name": "Zay Flowers", "team": "BAL", "position": "WR", "adp": 64.3, "tier": 4},
    {"rank": 65, "name": "David Montgomery", "team": "DET", "position": "RB", "adp": 65.2, "tier": 4},
    {"rank": 66, "name": "Trey McBride", "team": "ARI", "position": "TE", "adp": 66.1, "tier": 4},
    {"rank": 67, "name": "Zamir White", "team": "LV", "position": "RB", "adp": 67.4, "tier": 4},
    {"rank": 68, "name": "Hollywood Brown", "team": "KC", "position": "WR", "adp": 68.2, "tier": 4},
    {"rank": 69, "name": "C.J. Stroud", "team": "HOU", "position": "QB", "adp": 69.1, "tier": 4},
    {"rank": 70, "name": "Christian Watson", "team": "GB", "position": "WR", "adp": 70.1, "tier": 4},
    {"rank": 71, "name": "Najee Harris", "team": "PIT", "position": "RB", "adp": 71.3, "tier": 4},
    {"rank": 72, "name": "Jordan Addison", "team": "MIN", "position": "WR", "adp": 72.2, "tier": 4},
    {"rank": 73, "name": "Alvin Kamara", "team": "NO", "position": "RB", "adp": 73.4, "tier": 4},
    {"rank": 74, "name": "Michael Pittman Jr.", "team": "IND", "position": "WR", "adp": 74.1, "tier": 4},
    {"rank": 75, "name": "Ladd McConkey", "team": "LAC", "position": "WR", "adp": 75.3, "tier": 4},
    {"rank": 76, "name": "Kyle Pitts", "team": "ATL", "position": "TE", "adp": 76.2, "tier": 4},
    {"rank": 77, "name": "Javonte Williams", "team": "DEN", "position": "RB", "adp": 77.1, "tier": 4},
    {"rank": 78, "name": "Brian Thomas Jr.", "team": "JAX", "position": "WR", "adp": 78.4, "tier": 4},
    {"rank": 79, "name": "Joe Mixon", "team": "HOU", "position": "RB", "adp": 79.2, "tier": 4},
    {"rank": 80, "name": "Xavier Worthy", "team": "KC", "position": "WR", "adp": 80.3, "tier": 4},
    {"rank": 81, "name": "Jerome Ford", "team": "CLE", "position": "RB", "adp": 81.1, "tier": 4},
    {"rank": 82, "name": "Deebo Samuel", "team": "SF", "position": "WR", "adp": 82.4, "tier": 4},
    {"rank": 83, "name": "Dallas Goedert", "team": "PHI", "position": "TE", "adp": 83.2, "tier": 4},
    {"rank": 84, "name": "Deon Jackson", "team": "IND", "position": "RB", "adp": 84.3, "tier": 4},
    {"rank": 85, "name": "Jaxon Smith-Njigba", "team": "SEA", "position": "WR", "adp": 85.1, "tier": 4},
    {"rank": 86, "name": "Trevor Lawrence", "team": "JAX", "position": "QB", "adp": 86.4, "tier": 4},
    {"rank": 87, "name": "Tyler Lockett", "team": "SEA", "position": "WR", "adp": 87.2, "tier": 4},
    {"rank": 88, "name": "Gus Edwards", "team": "LAC", "position": "RB", "adp": 88.1, "tier": 4},
    {"rank": 89, "name": "Rashee Rice", "team": "KC", "position": "WR", "adp": 89.3, "tier": 4},
    {"rank": 90, "name": "Kendre Miller", "team": "NO", "position": "RB", "adp": 90.2, "tier": 4},
    {"rank": 91, "name": "Wandale Robinson", "team": "NYG", "position": "WR", "adp": 91.4, "tier": 4},
    {"rank": 92, "name": "Jake Ferguson", "team": "DAL", "position": "TE", "adp": 92.1, "tier": 4},
    {"rank": 93, "name": "Khalil Shakir", "team": "BUF", "position": "WR", "adp": 93.3, "tier": 4},
    {"rank": 94, "name": "Bo Nix", "team": "DEN", "position": "QB", "adp": 94.2, "tier": 4},
    {"rank": 95, "name": "Jakobi Meyers", "team": "LV", "position": "WR", "adp": 95.1, "tier": 4},
    {"rank": 96, "name": "Antonio Gibson", "team": "NE", "position": "RB", "adp": 96.4, "tier": 4},
    {"rank": 97, "name": "DeAndre Hopkins", "team": "TEN", "position": "WR", "adp": 97.2, "tier": 4},
    {"rank": 98, "name": "Isaiah Likely", "team": "BAL", "position": "TE", "adp": 98.3, "tier": 4},
    {"rank": 99, "name": "Tyjae Spears", "team": "TEN", "position": "RB", "adp": 99.1, "tier": 4},
    {"rank": 100, "name": "Geno Smith", "team": "SEA", "position": "QB", "adp": 100.2, "tier": 4},

    # TIER 5 - Solid Starters/Flex (Ranks 101-150)
    {"rank": 101, "name": "Jaylen Waddle", "team": "MIA", "position": "WR", "adp": 101.3, "tier": 5},
    {"rank": 102, "name": "Tyler Allgeier", "team": "ATL", "position": "RB", "adp": 102.1, "tier": 5},
    {"rank": 103, "name": "Jameson Williams", "team": "DET", "position": "WR", "adp": 103.4, "tier": 5},
    {"rank": 104, "name": "Raheem Mostert", "team": "MIA", "position": "RB", "adp": 104.2, "tier": 5},
    {"rank": 105, "name": "Pat Freiermuth", "team": "PIT", "position": "TE", "adp": 105.1, "tier": 5},
    {"rank": 106, "name": "Ameer Abdullah", "team": "LV", "position": "RB", "adp": 106.3, "tier": 5},
    {"rank": 107, "name": "Jayden Reed", "team": "GB", "position": "WR", "adp": 107.2, "tier": 5},
    {"rank": 108, "name": "J.K. Dobbins", "team": "LAC", "position": "RB", "adp": 108.4, "tier": 5},  
    {"rank": 109, "name": "Daniel Jones", "team": "NYG", "position": "QB", "adp": 109.1, "tier": 5},
    {"rank": 110, "name": "Adam Thielen", "team": "CAR", "position": "WR", "adp": 110.3, "tier": 5},
    {"rank": 111, "name": "Chuba Hubbard", "team": "CAR", "position": "RB", "adp": 111.2, "tier": 5},
    {"rank": 112, "name": "Tyler Higbee", "team": "LAR", "position": "TE", "adp": 112.1, "tier": 5},
    {"rank": 113, "name": "Brandin Cooks", "team": "DAL", "position": "WR", "adp": 113.4, "tier": 5},
    {"rank": 114, "name": "Aaron Rodgers", "team": "NYJ", "position": "QB", "adp": 114.2, "tier": 5},
    {"rank": 115, "name": "Miles Sanders", "team": "CAR", "position": "RB", "adp": 115.3, "tier": 5},
    {"rank": 116, "name": "Curtis Samuel", "team": "BUF", "position": "WR", "adp": 116.1, "tier": 5},
    {"rank": 117, "name": "D'Andre Swift", "team": "CHI", "position": "RB", "adp": 117.4, "tier": 5},
    {"rank": 118, "name": "Cole Kmet", "team": "CHI", "position": "TE", "adp": 118.2, "tier": 5},
    {"rank": 119, "name": "Jerry Jeudy", "team": "CLE", "position": "WR", "adp": 119.3, "tier": 5},
    {"rank": 120, "name": "Kareem Hunt", "team": "KC", "position": "RB", "adp": 120.1, "tier": 5},
    {"rank": 121, "name": "Elijah Moore", "team": "CLE", "position": "WR", "adp": 121.4, "tier": 5},
    {"rank": 122, "name": "Darren Waller", "team": "NYG", "position": "TE", "adp": 122.2, "tier": 5},
    {"rank": 123, "name": "Russell Wilson", "team": "PIT", "position": "QB", "adp": 123.3, "tier": 5},
    {"rank": 124, "name": "Dandre Swift", "team": "CHI", "position": "RB", "adp": 124.1, "tier": 5},
    {"rank": 125, "name": "Mike Williams", "team": "NYJ", "position": "WR", "adp": 125.4, "tier": 5},
    {"rank": 126, "name": "Hunter Henry", "team": "NE", "position": "TE", "adp": 126.2, "tier": 5},
    {"rank": 127, "name": "Jalen Tolbert", "team": "DAL", "position": "WR", "adp": 127.3, "tier": 5},
    {"rank": 128, "name": "Kirk Cousins", "team": "ATL", "position": "QB", "adp": 128.1, "tier": 5},
    {"rank": 129, "name": "Roschon Johnson", "team": "CHI", "position": "RB", "adp": 129.4, "tier": 5},
    {"rank": 130, "name": "Darnell Mooney", "team": "ATL", "position": "WR", "adp": 130.2, "tier": 5},
    {"rank": 131, "name": "Rico Dowdle", "team": "DAL", "position": "RB", "adp": 131.3, "tier": 5},
    {"rank": 132, "name": "Noah Brown", "team": "WAS", "position": "WR", "adp": 132.1, "tier": 5},
    {"rank": 133, "name": "Cade Otton", "team": "TB", "position": "TE", "adp": 133.4, "tier": 5},
    {"rank": 134, "name": "Ezekiel Elliott", "team": "DAL", "position": "RB", "adp": 134.2, "tier": 5},
    {"rank": 135, "name": "Derek Carr", "team": "NO", "position": "QB", "adp": 135.3, "tier": 5},
    {"rank": 136, "name": "Josh Palmer", "team": "LAC", "position": "WR", "adp": 136.1, "tier": 5},
    {"rank": 137, "name": "Cam Akers", "team": "HOU", "position": "RB", "adp": 137.4, "tier": 5},
    {"rank": 138, "name": "Tutu Atwell", "team": "LAR", "position": "WR", "adp": 138.2, "tier": 5},
    {"rank": 139, "name": "Juwan Johnson", "team": "NO", "position": "TE", "adp": 139.3, "tier": 5},
    {"rank": 140, "name": "Trey Sermon", "team": "IND", "position": "RB", "adp": 140.1, "tier": 5},
    {"rank": 141, "name": "Cedrick Wilson Jr.", "team": "NO", "position": "WR", "adp": 141.4, "tier": 5},
    {"rank": 142, "name": "Anthony Desir", "team": "TB", "position": "RB", "adp": 142.2, "tier": 5},
    {"rank": 143, "name": "Will Dissly", "team": "LAC", "position": "TE", "adp": 143.3, "tier": 5},
    {"rank": 144, "name": "Mack Hollins", "team": "BUF", "position": "WR", "adp": 144.1, "tier": 5},
    {"rank": 145, "name": "Justin Fields", "team": "PIT", "position": "QB", "adp": 145.4, "tier": 5},
    {"rank": 146, "name": "Kenneth Gainwell", "team": "PHI", "position": "RB", "adp": 146.2, "tier": 5},
    {"rank": 147, "name": "Parris Campbell", "team": "NYG", "position": "WR", "adp": 147.3, "tier": 5},
    {"rank": 148, "name": "Tyler Conklin", "team": "NYJ", "position": "TE", "adp": 148.1, "tier": 5},
    {"rank": 149, "name": "Samaje Perine", "team": "KC", "position": "RB", "adp": 149.4, "tier": 5},
    {"rank": 150, "name": "DeVante Parker", "team": "NE", "position": "WR", "adp": 150.2, "tier": 5},

    # TIER 6 - Bench/Upside (Ranks 151-200)
    {"rank": 151, "name": "Jaylen Warren", "team": "PIT", "position": "RB", "adp": 151.3, "tier": 6},
    {"rank": 152, "name": "Michael Wilson", "team": "ARI", "position": "WR", "adp": 152.1, "tier": 6},
    {"rank": 153, "name": "Brock Bowers", "team": "LV", "position": "TE", "adp": 153.4, "tier": 6},
    {"rank": 154, "name": "Clyde Edwards-Helaire", "team": "KC", "position": "RB", "adp": 154.2, "tier": 6},
    {"rank": 155, "name": "Gardner Minshew", "team": "LV", "position": "QB", "adp": 155.3, "tier": 6},
    {"rank": 156, "name": "Romeo Doubs", "team": "GB", "position": "WR", "adp": 156.1, "tier": 6},
    {"rank": 157, "name": "Ty Chandler", "team": "MIN", "position": "RB", "adp": 157.4, "tier": 6},
    {"rank": 158, "name": "Jalen McMillan", "team": "TB", "position": "WR", "adp": 158.2, "tier": 6},
    {"rank": 159, "name": "Jayden Reed", "team": "GB", "position": "WR", "adp": 159.2, "tier": 6},  # Keep original as requested
    {"rank": 160, "name": "Romeo Doubs", "team": "GB", "position": "WR", "adp": 160.1, "tier": 6}, # Keep original as requested
    {"rank": 161, "name": "Dontayvion Wicks", "team": "GB", "position": "WR", "adp": 161.4, "tier": 6},  # Keep original as requested
    {"rank": 162, "name": "Tyler Boyd", "team": "TEN", "position": "WR", "adp": 162.3, "tier": 6},  # Keep original as requested
    {"rank": 163, "name": "Wan'Dale Robinson", "team": "NYG", "position": "WR", "adp": 163.1, "tier": 6},  # Keep original as requested
    {"rank": 164, "name": "Dameon Pierce", "team": "HOU", "position": "RB", "adp": 164.4, "tier": 6},
    {"rank": 165, "name": "Aidan O'Connell", "team": "LV", "position": "QB", "adp": 165.2, "tier": 6},
    {"rank": 166, "name": "Quentin Johnston", "team": "LAC", "position": "WR", "adp": 166.3, "tier": 6},
    {"rank": 167, "name": "Ray Davis", "team": "BUF", "position": "RB", "adp": 167.1, "tier": 6},
    {"rank": 168, "name": "Luke Musgrave", "team": "GB", "position": "TE", "adp": 168.4, "tier": 6},
    {"rank": 169, "name": "Tre Tucker", "team": "LV", "position": "WR", "adp": 169.2, "tier": 6},
    {"rank": 170, "name": "Jordan Mason", "team": "SF", "position": "RB", "adp": 170.3, "tier": 6},
    {"rank": 171, "name": "Keon Coleman", "team": "BUF", "position": "WR", "adp": 171.1, "tier": 6},
    {"rank": 172, "name": "Hayden Hurst", "team": "LAC", "position": "TE", "adp": 172.4, "tier": 6},
    {"rank": 173, "name": "Jaleel McLaughlin", "team": "DEN", "position": "RB", "adp": 173.2, "tier": 6},
    {"rank": 174, "name": "Bryce Young", "team": "CAR", "position": "QB", "adp": 174.3, "tier": 6},
    {"rank": 175, "name": "Adonai Mitchell", "team": "IND", "position": "WR", "adp": 175.1, "tier": 6},
    {"rank": 176, "name": "Craig Reynolds", "team": "DET", "position": "RB", "adp": 176.4, "tier": 6},
    {"rank": 177, "name": "Tucker Kraft", "team": "GB", "position": "TE", "adp": 177.2, "tier": 6},
    {"rank": 178, "name": "Zach Charbonnet", "team": "SEA", "position": "RB", "adp": 178.3, "tier": 6},
    {"rank": 179, "name": "Jonnu Smith", "team": "MIA", "position": "TE", "adp": 179.1, "tier": 6},
    {"rank": 180, "name": "Jahan Dotson", "team": "WAS", "position": "WR", "adp": 180.4, "tier": 6},
    {"rank": 181, "name": "Justice Hill", "team": "BAL", "position": "RB", "adp": 181.2, "tier": 6},
    {"rank": 182, "name": "Mac Jones", "team": "JAX", "position": "QB", "adp": 182.3, "tier": 6},
    {"rank": 183, "name": "Darius Slayton", "team": "NYG", "position": "WR", "adp": 183.1, "tier": 6},
    {"rank": 184, "name": "Blake Corum", "team": "LAR", "position": "RB", "adp": 184.4, "tier": 6},
    {"rank": 185, "name": "Marquez Valdes-Scantling", "team": "BUF", "position": "WR", "adp": 185.2, "tier": 6},
    {"rank": 186, "name": "Mike Gesicki", "team": "CIN", "position": "TE", "adp": 186.3, "tier": 6},
    {"rank": 187, "name": "Tank Bigsby", "team": "JAX", "position": "RB", "adp": 187.1, "tier": 6},
    {"rank": 188, "name": "Sam Howell", "team": "SEA", "position": "QB", "adp": 188.4, "tier": 6},
    {"rank": 189, "name": "KJ Osborn", "team": "NE", "position": "WR", "adp": 189.2, "tier": 6},
    {"rank": 190, "name": "MarShawn Lloyd", "team": "GB", "position": "RB", "adp": 190.3, "tier": 6},
    {"rank": 191, "name": "Demarcus Robinson", "team": "LAR", "position": "WR", "adp": 191.1, "tier": 6},
    {"rank": 192, "name": "Chigoziem Okonkwo", "team": "TEN", "position": "TE", "adp": 192.4, "tier": 6},
    {"rank": 193, "name": "Keaton Mitchell", "team": "BAL", "position": "RB", "adp": 193.2, "tier": 6},
    {"rank": 194, "name": "Skyy Moore", "team": "KC", "position": "WR", "adp": 194.3, "tier": 6}, 
    {"rank": 195, "name": "Austin Hooper", "team": "NE", "position": "TE", "adp": 195.1, "tier": 6},
    {"rank": 196, "name": "AJ Dillon", "team": "GB", "position": "RB", "adp": 196.4, "tier": 6},
    {"rank": 197, "name": "Anthony Miller", "team": "BAL", "position": "WR", "adp": 197.2, "tier": 6},
    {"rank": 198, "name": "Malik Washington", "team": "MIA", "position": "WR", "adp": 198.3, "tier": 6},
    {"rank": 199, "name": "Drew Lock", "team": "NYG", "position": "QB", "adp": 199.1, "tier": 6},
    {"rank": 200, "name": "Audric Estime", "team": "DEN", "position": "RB", "adp": 200.4, "tier": 6},

    # TIER 7 - Deep Sleepers/Handcuffs (Ranks 201-300)
    {"rank": 201, "name": "Jermaine Burton", "team": "CIN", "position": "WR", "adp": 201.2, "tier": 7},
    {"rank": 202, "name": "Kimani Vidal", "team": "LAC", "position": "RB", "adp": 202.3, "tier": 7},
    {"rank": 203, "name": "Ricky Pearsall", "team": "SF", "position": "WR", "adp": 203.1, "tier": 7},
    {"rank": 204, "name": "Braelon Allen", "team": "NYJ", "position": "RB", "adp": 204.4, "tier": 7},
    {"rank": 205, "name": "Erick All", "team": "CIN", "position": "TE", "adp": 205.2, "tier": 7},
    {"rank": 206, "name": "Xavier Legette", "team": "CAR", "position": "WR", "adp": 206.3, "tier": 7},
    {"rank": 207, "name": "Isaiah Davis", "team": "NYJ", "position": "RB", "adp": 207.1, "tier": 7},
    {"rank": 208, "name": "Ben Skowronek", "team": "PIT", "position": "WR", "adp": 208.4, "tier": 7},
    {"rank": 209, "name": "Tylan Wallace", "team": "BAL", "position": "WR", "adp": 209.2, "tier": 7},
    {"rank": 210, "name": "Sean Tucker", "team": "TB", "position": "RB", "adp": 210.3, "tier": 7},
    {"rank": 211, "name": "Clayton Tune", "team": "ARI", "position": "QB", "adp": 211.1, "tier": 7},
    {"rank": 212, "name": "Devaughn Vele", "team": "DEN", "position": "WR", "adp": 212.4, "tier": 7},
    {"rank": 213, "name": "Bucky Irving", "team": "TB", "position": "RB", "adp": 213.2, "tier": 7},
    {"rank": 214, "name": "Ja'Lynn Polk", "team": "NE", "position": "WR", "adp": 214.3, "tier": 7},
    {"rank": 215, "name": "Dylan Laube", "team": "LV", "position": "RB", "adp": 215.1, "tier": 7},
    {"rank": 216, "name": "Jalen Coker", "team": "CAR", "position": "WR", "adp": 216.4, "tier": 7},
    {"rank": 217, "name": "Devin Culp", "team": "TB", "position": "TE", "adp": 217.2, "tier": 7},
    {"rank": 218, "name": "Troy Franklin", "team": "DEN", "position": "WR", "adp": 218.3, "tier": 7},
    {"rank": 219, "name": "Keilan Robinson", "team": "JAX", "position": "RB", "adp": 219.1, "tier": 7},
    {"rank": 220, "name": "Johnny Wilson", "team": "PHI", "position": "WR", "adp": 220.4, "tier": 7},
    {"rank": 221, "name": "Emari Demercado", "team": "ARI", "position": "RB", "adp": 221.2, "tier": 7},
    {"rank": 222, "name": "Ainias Smith", "team": "PHI", "position": "WR", "adp": 222.3, "tier": 7},
    {"rank": 223, "name": "Dalton Kincaid", "team": "BUF", "position": "TE", "adp": 223.1, "tier": 7},
    {"rank": 224, "name": "Devontez Walker", "team": "BAL", "position": "WR", "adp": 224.4, "tier": 7},
    {"rank": 225, "name": "Trey Benson", "team": "ARI", "position": "RB", "adp": 225.2, "tier": 7},
    {"rank": 226, "name": "Desmond Ridder", "team": "ARI", "position": "QB", "adp": 226.3, "tier": 7},
    {"rank": 227, "name": "Jacob Cowing", "team": "SF", "position": "WR", "adp": 227.1, "tier": 7},
    {"rank": 228, "name": "Jaylen Wright", "team": "MIA", "position": "RB", "adp": 228.4, "tier": 7},
    {"rank": 229, "name": "Luke McCaffrey", "team": "WAS", "position": "WR", "adp": 229.2, "tier": 7},
    {"rank": 230, "name": "Will Shipley", "team": "PHI", "position": "RB", "adp": 230.3, "tier": 7},
    {"rank": 231, "name": "Trey Palmer", "team": "TB", "position": "WR", "adp": 231.1, "tier": 7},
    {"rank": 232, "name": "Jordan Whittington", "team": "LAR", "position": "WR", "adp": 232.4, "tier": 7},
    {"rank": 233, "name": "Chris Rodriguez Jr.", "team": "WAS", "position": "RB", "adp": 233.2, "tier": 7},
    {"rank": 234, "name": "Malik Nabers", "team": "NYG", "position": "WR", "adp": 234.3, "tier": 7},  # Duplicate name, different tier
    {"rank": 235, "name": "Jake Browning", "team": "CIN", "position": "QB", "adp": 235.1, "tier": 7},
    {"rank": 236, "name": "Kendall Fuller", "team": "MIA", "position": "WR", "adp": 236.4, "tier": 7},
    {"rank": 237, "name": "Hassan Haskins", "team": "TEN", "position": "RB", "adp": 237.2, "tier": 7},
    {"rank": 238, "name": "Dionte Johnson", "team": "CAR", "position": "WR", "adp": 238.3, "tier": 7},
    {"rank": 239, "name": "C.J. Beathard", "team": "MIA", "position": "QB", "adp": 239.1, "tier": 7},
    {"rank": 240, "name": "Mason Tipton", "team": "NO", "position": "WR", "adp": 240.4, "tier": 7},
    {"rank": 241, "name": "Frank Gore Jr.", "team": "BUF", "position": "RB", "adp": 241.2, "tier": 7},
    {"rank": 242, "name": "Jalen Reagor", "team": "LAC", "position": "WR", "adp": 242.3, "tier": 7},
    {"rank": 243, "name": "Michael Mayer", "team": "LV", "position": "TE", "adp": 243.1, "tier": 7},
    {"rank": 244, "name": "Charlie Jones", "team": "CIN", "position": "WR", "adp": 244.4, "tier": 7},
    {"rank": 245, "name": "Dare Ogunbowale", "team": "HOU", "position": "RB", "adp": 245.2, "tier": 7},
    {"rank": 246, "name": "Malik Cunningham", "team": "NE", "position": "QB", "adp": 246.3, "tier": 7},
    {"rank": 247, "name": "Ty Johnson", "team": "BUF", "position": "RB", "adp": 247.1, "tier": 7},
    {"rank": 248, "name": "Kendrick Bourne", "team": "NE", "position": "WR", "adp": 248.4, "tier": 7},
    {"rank": 249, "name": "Donald Parham Jr.", "team": "LAC", "position": "TE", "adp": 249.2, "tier": 7},
    {"rank": 250, "name": "Brandon Johnson", "team": "DEN", "position": "WR", "adp": 250.3, "tier": 7},
    {"rank": 251, "name": "Ameer Abdullah", "team": "LV", "position": "RB", "adp": 251.1, "tier": 7},  # Different tier
    {"rank": 252, "name": "Trent Sherfield", "team": "MIN", "position": "WR", "adp": 252.4, "tier": 7},
    {"rank": 253, "name": "Tanner Hudson", "team": "CIN", "position": "TE", "adp": 253.2, "tier": 7},
    {"rank": 254, "name": "Noah Gray", "team": "KC", "position": "TE", "adp": 254.3, "tier": 7},
    {"rank": 255, "name": "Anthony Firkser", "team": "DET", "position": "TE", "adp": 255.1, "tier": 7},
    {"rank": 256, "name": "Nathan Rourke", "team": "NYG", "position": "QB", "adp": 256.4, "tier": 7},
    {"rank": 257, "name": "Malachi Corley", "team": "NYJ", "position": "WR", "adp": 257.2, "tier": 7},
    {"rank": 258, "name": "Tommy DeVito", "team": "NYG", "position": "QB", "adp": 258.3, "tier": 7},
    {"rank": 259, "name": "Velus Jones Jr.", "team": "CHI", "position": "WR", "adp": 259.1, "tier": 7},
    {"rank": 260, "name": "Durham Smythe", "team": "MIA", "position": "TE", "adp": 260.4, "tier": 7},
    {"rank": 261, "name": "Rashod Bateman", "team": "BAL", "position": "WR", "adp": 261.2, "tier": 7},
    {"rank": 262, "name": "Tyler Badie", "team": "DEN", "position": "RB", "adp": 262.3, "tier": 7},
    {"rank": 263, "name": "Mike White", "team": "MIA", "position": "QB", "adp": 263.1, "tier": 7},
    {"rank": 264, "name": "Irv Smith Jr.", "team": "KC", "position": "TE", "adp": 264.4, "tier": 7},
    {"rank": 265, "name": "JaQuan Hardy", "team": "BUF", "position": "RB", "adp": 265.2, "tier": 7},
    {"rank": 266, "name": "Tyler Scott", "team": "CHI", "position": "WR", "adp": 266.3, "tier": 7},
    {"rank": 267, "name": "Anthony Richardson", "team": "IND", "position": "QB", "adp": 267.1, "tier": 7},  # Backup QB
    {"rank": 268, "name": "Parker Washington", "team": "JAX", "position": "WR", "adp": 268.4, "tier": 7},
    {"rank": 269, "name": "Zach Evans", "team": "LAR", "position": "RB", "adp": 269.2, "tier": 7},
    {"rank": 270, "name": "Robert Woods", "team": "HOU", "position": "WR", "adp": 270.3, "tier": 7},
    {"rank": 271, "name": "Kyahva Tezino", "team": "NO", "position": "RB", "adp": 271.1, "tier": 7},
    {"rank": 272, "name": "Taysom Hill", "team": "NO", "position": "TE", "adp": 272.4, "tier": 7},
    {"rank": 273, "name": "Taiwan Jones", "team": "BUF", "position": "RB", "adp": 273.2, "tier": 7},
    {"rank": 274, "name": "Kendall Milton", "team": "PHI", "position": "RB", "adp": 274.3, "tier": 7},
    {"rank": 275, "name": "Jarrett Stidham", "team": "DEN", "position": "QB", "adp": 275.1, "tier": 7},
    {"rank": 276, "name": "Quez Watkins", "team": "PIT", "position": "WR", "adp": 276.4, "tier": 7},
    {"rank": 277, "name": "Miller Forristall", "team": "TEN", "position": "TE", "adp": 277.2, "tier": 7},
    {"rank": 278, "name": "Alec Pierce", "team": "IND", "position": "WR", "adp": 278.3, "tier": 7},
    {"rank": 279, "name": "Kyle Juszczyk", "team": "SF", "position": "RB", "adp": 279.1, "tier": 7},
    {"rank": 280, "name": "Stone Smartt", "team": "LAC", "position": "TE", "adp": 280.4, "tier": 7},
    {"rank": 281, "name": "Daijun Edwards", "team": "GB", "position": "RB", "adp": 281.2, "tier": 7},
    {"rank": 282, "name": "Bailey Zappe", "team": "NE", "position": "QB", "adp": 282.3, "tier": 7},
    {"rank": 283, "name": "KJ Hamler", "team": "BUF", "position": "WR", "adp": 283.1, "tier": 7},
    {"rank": 284, "name": "Cam Rising", "team": "JAX", "position": "QB", "adp": 284.4, "tier": 7},
    {"rank": 285, "name": "Greg Dulcich", "team": "DEN", "position": "TE", "adp": 285.2, "tier": 7},
    {"rank": 286, "name": "Deuce Vaughn", "team": "DAL", "position": "RB", "adp": 286.3, "tier": 7},
    {"rank": 287, "name": "Mason Rudolph", "team": "TEN", "position": "QB", "adp": 287.1, "tier": 7},
    {"rank": 288, "name": "DJ Turner", "team": "LV", "position": "WR", "adp": 288.4, "tier": 7},
    {"rank": 289, "name": "Keaontay Ingram", "team": "KC", "position": "RB", "adp": 289.2, "tier": 7},
    {"rank": 290, "name": "Tanner McKee", "team": "PHI", "position": "QB", "adp": 290.3, "tier": 7},
    {"rank": 291, "name": "Reggie Roberson Jr.", "team": "ATL", "position": "WR", "adp": 291.1, "tier": 7},
    {"rank": 292, "name": "Charlie Kolar", "team": "BAL", "position": "TE", "adp": 292.4, "tier": 7},
    {"rank": 293, "name": "D'Onta Foreman", "team": "CLE", "position": "RB", "adp": 293.2, "tier": 7},
    {"rank": 294, "name": "Will Mallory", "team": "IND", "position": "TE", "adp": 294.3, "tier": 7},
    {"rank": 295, "name": "Jordan Travis", "team": "NYJ", "position": "QB", "adp": 295.1, "tier": 7},
    {"rank": 296, "name": "Chris Evans", "team": "CIN", "position": "RB", "adp": 296.4, "tier": 7},
    {"rank": 297, "name": "Malik Heath", "team": "GB", "position": "WR", "adp": 297.2, "tier": 7},
    {"rank": 298, "name": "Ben Skowronek", "team": "HOU", "position": "WR", "adp": 298.3, "tier": 7},
    {"rank": 299, "name": "Jake Haener", "team": "NO", "position": "QB", "adp": 299.1, "tier": 7},
    {"rank": 300, "name": "Jalen Guyton", "team": "DAL", "position": "WR", "adp": 300.4, "tier": 7},

    # TIER 8 - Deep Bench/Speculative (Ranks 301-500)
    # Kickers (32 total - one per team)
    {"rank": 301, "name": "Justin Tucker", "team": "BAL", "position": "K", "adp": 301.1, "tier": 8},
    {"rank": 302, "name": "Harrison Butker", "team": "KC", "position": "K", "adp": 302.2, "tier": 8},
    {"rank": 303, "name": "Tyler Bass", "team": "BUF", "position": "K", "adp": 303.3, "tier": 8},
    {"rank": 304, "name": "Jake Elliott", "team": "PHI", "position": "K", "adp": 304.1, "tier": 8},
    {"rank": 305, "name": "Daniel Carlson", "team": "LV", "position": "K", "adp": 305.2, "tier": 8},
    {"rank": 306, "name": "Younghoe Koo", "team": "ATL", "position": "K", "adp": 306.3, "tier": 8},
    {"rank": 307, "name": "Cameron Dicker", "team": "LAC", "position": "K", "adp": 307.1, "tier": 8},
    {"rank": 308, "name": "Chris Boswell", "team": "PIT", "position": "K", "adp": 308.2, "tier": 8},
    {"rank": 309, "name": "Jason Sanders", "team": "MIA", "position": "K", "adp": 309.3, "tier": 8},
    {"rank": 310, "name": "Brandon McManus", "team": "GB", "position": "K", "adp": 310.1, "tier": 8},
    {"rank": 311, "name": "Wil Lutz", "team": "DEN", "position": "K", "adp": 311.2, "tier": 8},
    {"rank": 312, "name": "Jake Moody", "team": "SF", "position": "K", "adp": 312.3, "tier": 8},
    {"rank": 313, "name": "Nick Folk", "team": "TEN", "position": "K", "adp": 313.1, "tier": 8},
    {"rank": 314, "name": "Cairo Santos", "team": "CHI", "position": "K", "adp": 314.2, "tier": 8},
    {"rank": 315, "name": "Jason Myers", "team": "SEA", "position": "K", "adp": 315.3, "tier": 8},
    {"rank": 316, "name": "Greg Zuerlein", "team": "NYJ", "position": "K", "adp": 316.1, "tier": 8},
    {"rank": 317, "name": "Evan McPherson", "team": "CIN", "position": "K", "adp": 317.2, "tier": 8},
    {"rank": 318, "name": "Matt Gay", "team": "IND", "position": "K", "adp": 318.3, "tier": 8},
    {"rank": 319, "name": "Dustin Hopkins", "team": "CLE", "position": "K", "adp": 319.1, "tier": 8},
    {"rank": 320, "name": "Graham Gano", "team": "NYG", "position": "K", "adp": 320.2, "tier": 8},
    {"rank": 321, "name": "Ka'imi Fairbairn", "team": "HOU", "position": "K", "adp": 321.3, "tier": 8},
    {"rank": 322, "name": "Blake Grupe", "team": "NO", "position": "K", "adp": 322.1, "tier": 8},
    {"rank": 323, "name": "Brandon Aubrey", "team": "DAL", "position": "K", "adp": 323.2, "tier": 8},
    {"rank": 324, "name": "Chase McLaughlin", "team": "TB", "position": "K", "adp": 324.3, "tier": 8},
    {"rank": 325, "name": "Matt Prater", "team": "ARI", "position": "K", "adp": 325.1, "tier": 8},
    {"rank": 326, "name": "Joshua Karty", "team": "LAR", "position": "K", "adp": 326.2, "tier": 8},
    {"rank": 327, "name": "Cade York", "team": "WAS", "position": "K", "adp": 327.3, "tier": 8},
    {"rank": 328, "name": "Anders Carlson", "team": "SF", "position": "K", "adp": 328.1, "tier": 8},
    {"rank": 329, "name": "Riley Patterson", "team": "DET", "position": "K", "adp": 329.2, "tier": 8},
    {"rank": 330, "name": "Eddy Pineiro", "team": "CAR", "position": "K", "adp": 330.3, "tier": 8},
    {"rank": 331, "name": "Joey Slye", "team": "NE", "position": "K", "adp": 331.1, "tier": 8},
    {"rank": 332, "name": "Spencer Shrader", "team": "JAX", "position": "K", "adp": 332.2, "tier": 8},

    # Defenses (32 total - one per team)
    {"rank": 333, "name": "Ravens", "team": "BAL", "position": "DST", "adp": 333.1, "tier": 8},
    {"rank": 334, "name": "49ers", "team": "SF", "position": "DST", "adp": 334.2, "tier": 8},
    {"rank": 335, "name": "Bills", "team": "BUF", "position": "DST", "adp": 335.3, "tier": 8},
    {"rank": 336, "name": "Cowboys", "team": "DAL", "position": "DST", "adp": 336.1, "tier": 8},
    {"rank": 337, "name": "Eagles", "team": "PHI", "position": "DST", "adp": 337.2, "tier": 8},
    {"rank": 338, "name": "Chiefs", "team": "KC", "position": "DST", "adp": 338.3, "tier": 8},
    {"rank": 339, "name": "Jets", "team": "NYJ", "position": "DST", "adp": 339.1, "tier": 8},
    {"rank": 340, "name": "Steelers", "team": "PIT", "position": "DST", "adp": 340.2, "tier": 8},
    {"rank": 341, "name": "Dolphins", "team": "MIA", "position": "DST", "adp": 341.3, "tier": 8},
    {"rank": 342, "name": "Browns", "team": "CLE", "position": "DST", "adp": 342.1, "tier": 8},
    {"rank": 343, "name": "Lions", "team": "DET", "position": "DST", "adp": 343.2, "tier": 8},
    {"rank": 344, "name": "Packers", "team": "GB", "position": "DST", "adp": 344.3, "tier": 8},
    {"rank": 345, "name": "Chargers", "team": "LAC", "position": "DST", "adp": 345.1, "tier": 8},
    {"rank": 346, "name": "Saints", "team": "NO", "position": "DST", "adp": 346.2, "tier": 8},
    {"rank": 347, "name": "Seahawks", "team": "SEA", "position": "DST", "adp": 347.3, "tier": 8},
    {"rank": 348, "name": "Vikings", "team": "MIN", "position": "DST", "adp": 348.1, "tier": 8},
    {"rank": 349, "name": "Broncos", "team": "DEN", "position": "DST", "adp": 349.2, "tier": 8},
    {"rank": 350, "name": "Texans", "team": "HOU", "position": "DST", "adp": 350.3, "tier": 8},
    {"rank": 351, "name": "Raiders", "team": "LV", "position": "DST", "adp": 351.1, "tier": 8},
    {"rank": 352, "name": "Bengals", "team": "CIN", "position": "DST", "adp": 352.2, "tier": 8},
    {"rank": 353, "name": "Rams", "team": "LAR", "position": "DST", "adp": 353.3, "tier": 8},
    {"rank": 354, "name": "Colts", "team": "IND", "position": "DST", "adp": 354.1, "tier": 8},
    {"rank": 355, "name": "Cardinals", "team": "ARI", "position": "DST", "adp": 355.2, "tier": 8},
    {"rank": 356, "name": "Bears", "team": "CHI", "position": "DST", "adp": 356.3, "tier": 8},
    {"rank": 357, "name": "Falcons", "team": "ATL", "position": "DST", "adp": 357.1, "tier": 8},
    {"rank": 358, "name": "Buccaneers", "team": "TB", "position": "DST", "adp": 358.2, "tier": 8},
    {"rank": 359, "name": "Patriots", "team": "NE", "position": "DST", "adp": 359.3, "tier": 8},
    {"rank": 360, "name": "Titans", "team": "TEN", "position": "DST", "adp": 360.1, "tier": 8},
    {"rank": 361, "name": "Commanders", "team": "WAS", "position": "DST", "adp": 361.2, "tier": 8},
    {"rank": 362, "name": "Giants", "team": "NYG", "position": "DST", "adp": 362.3, "tier": 8},
    {"rank": 363, "name": "Jaguars", "team": "JAX", "position": "DST", "adp": 363.1, "tier": 8},
    {"rank": 364, "name": "Panthers", "team": "CAR", "position": "DST", "adp": 364.2, "tier": 8},

    # Additional QB depth (to reach 100+ QBs)
    {"rank": 365, "name": "Jacoby Brissett", "team": "NE", "position": "QB", "adp": 365.3, "tier": 8},
    {"rank": 366, "name": "Tyler Huntley", "team": "MIA", "position": "QB", "adp": 366.1, "tier": 8},
    {"rank": 367, "name": "Jameis Winston", "team": "CLE", "position": "QB", "adp": 367.2, "tier": 8},
    {"rank": 368, "name": "Andy Dalton", "team": "CAR", "position": "QB", "adp": 368.3, "tier": 8},
    {"rank": 369, "name": "Cooper Rush", "team": "DAL", "position": "QB", "adp": 369.1, "tier": 8},
    {"rank": 370, "name": "Mitch Trubisky", "team": "BUF", "position": "QB", "adp": 370.2, "tier": 8},
    {"rank": 371, "name": "Tyrod Taylor", "team": "NYG", "position": "QB", "adp": 371.3, "tier": 8},
    {"rank": 372, "name": "Ryan Tannehill", "team": "TEN", "position": "QB", "adp": 372.1, "tier": 8},
    {"rank": 373, "name": "Joshua Dobbs", "team": "SF", "position": "QB", "adp": 373.2, "tier": 8},
    {"rank": 374, "name": "Case Keenum", "team": "HOU", "position": "QB", "adp": 374.3, "tier": 8},
    {"rank": 375, "name": "Nick Foles", "team": "IND", "position": "QB", "adp": 375.1, "tier": 8},
    {"rank": 376, "name": "Blaine Gabbert", "team": "KC", "position": "QB", "adp": 376.2, "tier": 8},
    {"rank": 377, "name": "Joe Flacco", "team": "IND", "position": "QB", "adp": 377.3, "tier": 8},
    {"rank": 378, "name": "Matt Ryan", "team": "ATL", "position": "QB", "adp": 378.1, "tier": 8},
    {"rank": 379, "name": "Carson Wentz", "team": "WAS", "position": "QB", "adp": 379.2, "tier": 8},
    {"rank": 380, "name": "Mitchell Trubisky", "team": "PIT", "position": "QB", "adp": 380.3, "tier": 8},
    {"rank": 381, "name": "Teddy Bridgewater", "team": "MIA", "position": "QB", "adp": 381.1, "tier": 8},
    {"rank": 382, "name": "Ryan Fitzpatrick", "team": "NYJ", "position": "QB", "adp": 382.2, "tier": 8},
    {"rank": 383, "name": "Blake Bortles", "team": "GB", "position": "QB", "adp": 383.3, "tier": 8},
    {"rank": 384, "name": "Chad Henne", "team": "KC", "position": "QB", "adp": 384.1, "tier": 8},

    # Additional RB depth (to reach 150+ RBs)
    {"rank": 385, "name": "Boston Scott", "team": "PHI", "position": "RB", "adp": 385.2, "tier": 8},
    {"rank": 386, "name": "Jerick McKinnon", "team": "KC", "position": "RB", "adp": 386.3, "tier": 8},
    {"rank": 387, "name": "La'Rod Stephens-Howling", "team": "PIT", "position": "RB", "adp": 387.1, "tier": 8},
    {"rank": 388, "name": "Cordarrelle Patterson", "team": "PIT", "position": "RB", "adp": 388.2, "tier": 8},
    {"rank": 389, "name": "Latavius Murray", "team": "BUF", "position": "RB", "adp": 389.3, "tier": 8},
    {"rank": 390, "name": "Alex Collins", "team": "SEA", "position": "RB", "adp": 390.1, "tier": 8},
    {"rank": 391, "name": "Devonta Freeman", "team": "NO", "position": "RB", "adp": 391.2, "tier": 8},
    {"rank": 392, "name": "Jordan Howard", "team": "HOU", "position": "RB", "adp": 392.3, "tier": 8},
    {"rank": 393, "name": "Matt Breida", "team": "NYG", "position": "RB", "adp": 393.1, "tier": 8},
    {"rank": 394, "name": "Duke Johnson", "team": "BUF", "position": "RB", "adp": 394.2, "tier": 8},
    {"rank": 395, "name": "Nyheim Hines", "team": "CLE", "position": "RB", "adp": 395.3, "tier": 8},
    {"rank": 396, "name": "Phillip Lindsay", "team": "IND", "position": "RB", "adp": 396.1, "tier": 8},
    {"rank": 397, "name": "Dare Ogunbowale", "team": "WIS", "position": "RB", "adp": 397.2, "tier": 8},
    {"rank": 398, "name": "Deon Jackson", "team": "CLE", "position": "RB", "adp": 398.3, "tier": 8},
    {"rank": 399, "name": "Jeff Wilson Jr.", "team": "MIA", "position": "RB", "adp": 399.1, "tier": 8},
    {"rank": 400, "name": "Hassan Haskins", "team": "LAC", "position": "RB", "adp": 400.2, "tier": 8},

    # Additional WR depth (to reach 200+ WRs)
    {"rank": 401, "name": "Golden Tate", "team": "NYG", "position": "WR", "adp": 401.3, "tier": 8},
    {"rank": 402, "name": "Emmanuel Sanders", "team": "BUF", "position": "WR", "adp": 402.1, "tier": 8},
    {"rank": 403, "name": "Sterling Shepard", "team": "TB", "position": "WR", "adp": 403.2, "tier": 8},
    {"rank": 404, "name": "John Brown", "team": "LV", "position": "WR", "adp": 404.3, "tier": 8},
    {"rank": 405, "name": "Cole Beasley", "team": "TB", "position": "WR", "adp": 405.1, "tier": 8},
    {"rank": 406, "name": "Sammy Watkins", "team": "KC", "position": "WR", "adp": 406.2, "tier": 8},
    {"rank": 407, "name": "Preston Williams", "team": "MIA", "position": "WR", "adp": 407.3, "tier": 8},
    {"rank": 408, "name": "Allen Lazard", "team": "NYJ", "position": "WR", "adp": 408.1, "tier": 8},
    {"rank": 409, "name": "Mecole Hardman", "team": "KC", "position": "WR", "adp": 409.2, "tier": 8},
    {"rank": 410, "name": "Dante Pettis", "team": "CHI", "position": "WR", "adp": 410.3, "tier": 8},
    {"rank": 411, "name": "Isaiah Ford", "team": "MIA", "position": "WR", "adp": 411.1, "tier": 8},
    {"rank": 412, "name": "Chris Conley", "team": "HOU", "position": "WR", "adp": 412.2, "tier": 8},
    {"rank": 413, "name": "Robby Anderson", "team": "ARI", "position": "WR", "adp": 413.3, "tier": 8},
    {"rank": 414, "name": "Russell Gage", "team": "TB", "position": "WR", "adp": 414.1, "tier": 8},
    {"rank": 415, "name": "Olamide Zaccheaus", "team": "WAS", "position": "WR", "adp": 415.2, "tier": 8},
    {"rank": 416, "name": "Kalif Raymond", "team": "DET", "position": "WR", "adp": 416.3, "tier": 8},
    {"rank": 417, "name": "Nico Collins", "team": "HOU", "position": "WR", "adp": 417.1, "tier": 8},
    {"rank": 418, "name": "Tim Patrick", "team": "DEN", "position": "WR", "adp": 418.2, "tier": 8},
    {"rank": 419, "name": "N'Keal Harry", "team": "CHI", "position": "WR", "adp": 419.3, "tier": 8},
    {"rank": 420, "name": "Gabriel Davis", "team": "JAX", "position": "WR", "adp": 420.1, "tier": 8},
    {"rank": 421, "name": "Allen Robinson", "team": "PIT", "position": "WR", "adp": 421.2, "tier": 8},
    {"rank": 422, "name": "Marquise Goodwin", "team": "KC", "position": "WR", "adp": 422.3, "tier": 8},
    {"rank": 423, "name": "Jalen Guyton", "team": "LAC", "position": "WR", "adp": 423.1, "tier": 8},
    {"rank": 424, "name": "Donovan Peoples-Jones", "team": "DET", "position": "WR", "adp": 424.2, "tier": 8},
    {"rank": 425, "name": "Laviska Shenault Jr.", "team": "SEA", "position": "WR", "adp": 425.3, "tier": 8},
    {"rank": 426, "name": "Byron Pringle", "team": "WAS", "position": "WR", "adp": 426.1, "tier": 8},
    {"rank": 427, "name": "Terrace Marshall Jr.", "team": "CAR", "position": "WR", "adp": 427.2, "tier": 8},
    {"rank": 428, "name": "Collin Johnson", "team": "NYG", "position": "WR", "adp": 428.3, "tier": 8},
    {"rank": 429, "name": "Anthony Schwartz", "team": "CLE", "position": "WR", "adp": 429.1, "tier": 8},
    {"rank": 430, "name": "Dezmon Patmon", "team": "IND", "position": "WR", "adp": 430.2, "tier": 8},
    {"rank": 431, "name": "Isaiah McKenzie", "team": "IND", "position": "WR", "adp": 431.3, "tier": 8},
    {"rank": 432, "name": "Braxton Berrios", "team": "MIA", "position": "WR", "adp": 432.1, "tier": 8},
    {"rank": 433, "name": "Ray-Ray McCloud", "team": "ATL", "position": "WR", "adp": 433.2, "tier": 8},
    {"rank": 434, "name": "Gunner Olszewski", "team": "PIT", "position": "WR", "adp": 434.3, "tier": 8},
    {"rank": 435, "name": "Alex Erickson", "team": "CAR", "position": "WR", "adp": 435.1, "tier": 8},
    {"rank": 436, "name": "River Cracraft", "team": "MIA", "position": "WR", "adp": 436.2, "tier": 8},
    {"rank": 437, "name": "Marcus Johnson", "team": "SF", "position": "WR", "adp": 437.3, "tier": 8},
    {"rank": 438, "name": "Keeelan Doss", "team": "LV", "position": "WR", "adp": 438.1, "tier": 8},
    {"rank": 439, "name": "Devin Gray", "team": "ATL", "position": "WR", "adp": 439.2, "tier": 8},
    {"rank": 440, "name": "Kyle Phillips", "team": "TEN", "position": "WR", "adp": 440.3, "tier": 8},

    # Additional TE depth (to reach 100+ TEs)
    {"rank": 441, "name": "Noah Fant", "team": "SEA", "position": "TE", "adp": 441.1, "tier": 8},
    {"rank": 442, "name": "Albert Okwuegbunam", "team": "DEN", "position": "TE", "adp": 442.2, "tier": 8},
    {"rank": 443, "name": "Logan Thomas", "team": "WAS", "position": "TE", "adp": 443.3, "tier": 8},
    {"rank": 444, "name": "Robert Tonyan", "team": "CHI", "position": "TE", "adp": 444.1, "tier": 8},
    {"rank": 445, "name": "Brevin Jordan", "team": "HOU", "position": "TE", "adp": 445.2, "tier": 8},
    {"rank": 446, "name": "Tyler Kroft", "team": "SF", "position": "TE", "adp": 446.3, "tier": 8},
    {"rank": 447, "name": "Mo Alie-Cox", "team": "IND", "position": "TE", "adp": 447.1, "tier": 8},
    {"rank": 448, "name": "Jimmy Graham", "team": "NO", "position": "TE", "adp": 448.2, "tier": 8},
    {"rank": 449, "name": "Zach Ertz", "team": "WAS", "position": "TE", "adp": 449.3, "tier": 8},
    {"rank": 450, "name": "Cameron Brate", "team": "TB", "position": "TE", "adp": 450.1, "tier": 8},
    {"rank": 451, "name": "Gerald Everett", "team": "CHI", "position": "TE", "adp": 451.2, "tier": 8},
    {"rank": 452, "name": "Foster Moreau", "team": "NO", "position": "TE", "adp": 452.3, "tier": 8},
    {"rank": 453, "name": "Pharaoh Brown", "team": "SEA", "position": "TE", "adp": 453.1, "tier": 8},
    {"rank": 454, "name": "Jeremy Ruckert", "team": "NYJ", "position": "TE", "adp": 454.2, "tier": 8},
    {"rank": 455, "name": "Johnny Mundt", "team": "MIN", "position": "TE", "adp": 455.3, "tier": 8},
    {"rank": 456, "name": "Harrison Bryant", "team": "LV", "position": "TE", "adp": 456.1, "tier": 8},
    {"rank": 457, "name": "Jordan Akins", "team": "CLE", "position": "TE", "adp": 457.2, "tier": 8},
    {"rank": 458, "name": "C.J. Uzomah", "team": "NYJ", "position": "TE", "adp": 458.3, "tier": 8},
    {"rank": 459, "name": "Marcedes Lewis", "team": "CHI", "position": "TE", "adp": 459.1, "tier": 8},
    {"rank": 460, "name": "Jack Stoll", "team": "PHI", "position": "TE", "adp": 460.2, "tier": 8},
    {"rank": 461, "name": "Nick Vannett", "team": "NO", "position": "TE", "adp": 461.3, "tier": 8},
    {"rank": 462, "name": "Tyler Higbee", "team": "LAR", "position": "TE", "adp": 462.1, "tier": 8},
    {"rank": 463, "name": "Ian Thomas", "team": "CAR", "position": "TE", "adp": 463.2, "tier": 8},
    {"rank": 464, "name": "Ryan Griffin", "team": "CHI", "position": "TE", "adp": 464.3, "tier": 8},
    {"rank": 465, "name": "Jesse James", "team": "LV", "position": "TE", "adp": 465.1, "tier": 8},
    {"rank": 466, "name": "Deon Yelder", "team": "LV", "position": "TE", "adp": 466.2, "tier": 8},
    {"rank": 467, "name": "Dan Arnold", "team": "JAX", "position": "TE", "adp": 467.3, "tier": 8},
    {"rank": 468, "name": "James O'Shaughnessy", "team": "JAX", "position": "TE", "adp": 468.1, "tier": 8},
    {"rank": 469, "name": "Eric Saubert", "team": "DEN", "position": "TE", "adp": 469.2, "tier": 8},
    {"rank": 470, "name": "Anthony Firkser", "team": "ATL", "position": "TE", "adp": 470.3, "tier": 8},
    {"rank": 471, "name": "Ross Dwelley", "team": "SF", "position": "TE", "adp": 471.1, "tier": 8},
    {"rank": 472, "name": "Adam Shaheen", "team": "HOU", "position": "TE", "adp": 472.2, "tier": 8},
    {"rank": 473, "name": "Matt Orzech", "team": "BAL", "position": "TE", "adp": 473.3, "tier": 8},
    {"rank": 474, "name": "David Wells", "team": "TB", "position": "TE", "adp": 474.1, "tier": 8},
    {"rank": 475, "name": "Josiah Deguara", "team": "GB", "position": "TE", "adp": 475.2, "tier": 8},
    {"rank": 476, "name": "John FitzPatrick", "team": "ATL", "position": "TE", "adp": 476.3, "tier": 8},
    {"rank": 477, "name": "Kendall Blanton", "team": "LAR", "position": "TE", "adp": 477.1, "tier": 8},
    {"rank": 478, "name": "Trevon Wesco", "team": "NYJ", "position": "TE", "adp": 478.2, "tier": 8},
    {"rank": 479, "name": "Johnny Stanton", "team": "LV", "position": "TE", "adp": 479.3, "tier": 8},
    {"rank": 480, "name": "Thaddeus Moss", "team": "CIN", "position": "TE", "adp": 480.1, "tier": 8},

    # Fill remaining spots to 500
    {"rank": 481, "name": "Cody Thompson", "team": "TB", "position": "WR", "adp": 481.2, "tier": 8},
    {"rank": 482, "name": "Chad Beebe", "team": "HOU", "position": "WR", "adp": 482.3, "tier": 8},
    {"rank": 483, "name": "Taiwan Jones", "team": "BUF", "position": "RB", "adp": 483.1, "tier": 8},
    {"rank": 484, "name": "Tony Jones Jr.", "team": "DEN", "position": "RB", "adp": 484.2, "tier": 8},
    {"rank": 485, "name": "JaMycal Hasty", "team": "JAX", "position": "RB", "adp": 485.3, "tier": 8},
    {"rank": 486, "name": "Godwin Igwebuike", "team": "SEA", "position": "RB", "adp": 486.1, "tier": 8},
    {"rank": 487, "name": "Jordan Wilkins", "team": "IND", "position": "RB", "adp": 487.2, "tier": 8},
    {"rank": 488, "name": "Rodney Smith", "team": "CAR", "position": "RB", "adp": 488.3, "tier": 8},
    {"rank": 489, "name": "Salvon Ahmed", "team": "MIA", "position": "RB", "adp": 489.1, "tier": 8},
    {"rank": 490, "name": "Qadree Ollison", "team": "PIT", "position": "RB", "adp": 490.2, "tier": 8},
    {"rank": 491, "name": "Alex Armah", "team": "NO", "position": "RB", "adp": 491.3, "tier": 8},
    {"rank": 492, "name": "C.J. Ham", "team": "MIN", "position": "RB", "adp": 492.1, "tier": 8},
    {"rank": 493, "name": "Patrick Ricard", "team": "BAL", "position": "RB", "adp": 493.2, "tier": 8},
    {"rank": 494, "name": "Keith Smith", "team": "ATL", "position": "RB", "adp": 494.3, "tier": 8},
    {"rank": 495, "name": "Alec Ingold", "team": "MIA", "position": "RB", "adp": 495.1, "tier": 8},
    {"rank": 496, "name": "Kyle Juszczyk", "team": "SF", "position": "RB", "adp": 496.2, "tier": 8},
    {"rank": 497, "name": "Dan Vitale", "team": "NE", "position": "RB", "adp": 497.3, "tier": 8},
    {"rank": 498, "name": "Nick Bellore", "team": "SEA", "position": "RB", "adp": 498.1, "tier": 8},
    {"rank": 499, "name": "Reggie Gilliam", "team": "BUF", "position": "RB", "adp": 499.2, "tier": 8},
    {"rank": 500, "name": "Jakob Johnson", "team": "LV", "position": "RB", "adp": 500.3, "tier": 8}
]

def generate_mock_rankings():
    """Generate the complete mock rankings structure"""
    return {
        "superflex_half_ppr": {
            "last_updated": "2025-08-07T10:00:00",
            "format": "superflex", 
            "scoring": "half_ppr",
            "players": COMPREHENSIVE_RANKINGS
        }
    }

if __name__ == "__main__":
    # Generate and print the complete rankings
    rankings = generate_mock_rankings()
    
    # Verify counts by position
    position_counts = {}
    for player in rankings["superflex_half_ppr"]["players"]:
        pos = player["position"]
        if pos not in position_counts:
            position_counts[pos] = 0
        position_counts[pos] += 1
    
    print("Position Distribution:")
    for pos, count in sorted(position_counts.items()):
        print(f"  {pos}: {count}")
    
    print(f"\nTotal Players: {len(rankings['superflex_half_ppr']['players'])}")
    
    # Generate the Python code to replace in the original file
    print("\n" + "="*50)
    print("PYTHON STRUCTURE TO REPLACE MOCK_RANKINGS:")
    print("="*50)
    
    import json
    print("MOCK_RANKINGS = " + json.dumps(rankings, indent=4))